In [2]:
from src.seq2seq import *

In [3]:
encoder = Encoder(64, 128, num_layers=2)

In [4]:
x = (55 * torch.rand(3, 6)).long()
x

tensor([[ 2, 33,  9,  7, 39, 10],
        [30, 39, 37, 45, 21, 26],
        [ 7, 31,  3, 46, 32, 30]])

In [5]:
e, state = encoder(x)

In [6]:
decoder = Decoder(64, 128, num_layers=2)

In [7]:
seq = (8*torch.rand(3, 4)).long()
seq

tensor([[3, 2, 6, 6],
        [4, 0, 3, 6],
        [4, 3, 4, 1]])

In [8]:
out, state = decoder(seq, state)

In [9]:
out.size()

torch.Size([3, 4, 10000])

In [10]:
state.size()

torch.Size([2, 3, 64])

In [11]:
out

tensor([[[-0.1372,  0.1223,  0.0183,  ...,  0.1562, -0.0203, -0.0434],
         [-0.1575,  0.0743,  0.0243,  ...,  0.1214, -0.0220,  0.0484],
         [-0.2050,  0.0573,  0.0463,  ...,  0.0006, -0.0591,  0.0478],
         [-0.2407,  0.0663,  0.0631,  ..., -0.1238, -0.0881,  0.0442]],

        [[ 0.0155,  0.1970,  0.1676,  ...,  0.0557,  0.0444,  0.0740],
         [-0.0706,  0.2137,  0.1683,  ...,  0.0732, -0.0136,  0.0538],
         [-0.1196,  0.1678,  0.1090,  ...,  0.0295, -0.0519,  0.0492],
         [-0.1973,  0.1301,  0.0756,  ..., -0.0785, -0.0748,  0.0611]],

        [[ 0.0181,  0.2370,  0.1121,  ...,  0.0177,  0.0986,  0.1190],
         [-0.0776,  0.2011,  0.1012,  ..., -0.0406,  0.0330,  0.0911],
         [-0.0914,  0.2465,  0.1014,  ..., -0.0768,  0.0245,  0.1239],
         [-0.1210,  0.3018,  0.0911,  ..., -0.0951, -0.0010,  0.0980]]],
       grad_fn=<AddBackward0>)

In [12]:
seq2seq = Seq2Seq(encoder, decoder, 1.0)
x.size(), seq.size()

(torch.Size([3, 6]), torch.Size([3, 4]))

In [13]:
outputs = seq2seq(x, seq)

In [14]:
outputs.shape

torch.Size([3, 4, 10000])