In [1]:
from src.seq2seq import *
from src.attention import *

In [2]:
encoder = Encoder(64, 128, num_layers=1)

In [3]:
x = (55 * torch.rand(3, 6)).long()
x

tensor([[19, 25, 35, 23, 41, 49],
        [51, 12, 21,  6, 26,  4],
        [25,  3, 42, 30, 21, 15]])

In [4]:
e, state = encoder(x)

In [5]:
decoder = Decoder(64, 128, num_layers=1)

In [6]:
seq = (8*torch.rand(3, 4)).long()
seq

tensor([[0, 6, 6, 6],
        [2, 4, 0, 3],
        [7, 5, 6, 1]])

In [7]:
out, state, attn = decoder(seq, state)

In [8]:
out.size()

torch.Size([3, 4, 10000])

In [9]:
state.size()

torch.Size([1, 3, 64])

In [10]:
attn

In [11]:
out

tensor([[[-0.0417, -0.1800, -0.1740,  ...,  0.2859,  0.0264, -0.1182],
         [ 0.1799,  0.1721, -0.0552,  ...,  0.4089, -0.1036, -0.4123],
         [ 0.2806,  0.3457, -0.0035,  ...,  0.4538, -0.1728, -0.4468],
         [ 0.3447,  0.4297,  0.0132,  ...,  0.4606, -0.1962, -0.4425]],

        [[-0.1723, -0.1256,  0.2111,  ...,  0.0418,  0.0576, -0.1713],
         [-0.1040, -0.0903,  0.3334,  ..., -0.0536,  0.2657, -0.1548],
         [-0.0698, -0.2314,  0.0554,  ...,  0.3750,  0.1118,  0.0213],
         [ 0.0182, -0.0055, -0.0027,  ...,  0.3107,  0.1379, -0.1572]],

        [[ 0.1172,  0.1758, -0.0843,  ...,  0.1631, -0.2188,  0.0425],
         [ 0.2589,  0.2307,  0.0037,  ...,  0.1695, -0.0486, -0.2261],
         [ 0.3625,  0.4149, -0.0696,  ...,  0.2777, -0.1315, -0.4714],
         [ 0.0544,  0.2721,  0.0215,  ...,  0.0779,  0.1665, -0.2125]]],
       grad_fn=<AddBackward0>)

In [12]:
seq2seq = Seq2Seq(encoder, decoder, 1.0)
x.size(), seq.size()

(torch.Size([3, 6]), torch.Size([3, 4]))

In [13]:
outputs, weights = seq2seq(x, seq)

In [14]:
outputs.shape

torch.Size([3, 4, 10000])

In [15]:
weights

In [79]:
dec_attn = AttentionDecoder(64, 128, 
                            num_layers=1, 
                            attn_layer=LocationAttention)

In [80]:
dec_attn(seq, state, e)[1].size()

torch.Size([1, 3, 64])

In [81]:
e.size()

torch.Size([3, 6, 64])

In [82]:
seq2seq = Seq2Seq(encoder, dec_attn, 1.0)
x.size(), seq.size()

(torch.Size([3, 6]), torch.Size([3, 4]))

In [83]:
outputs, weights = seq2seq(x, seq)

In [84]:
outputs.shape

torch.Size([3, 4, 10000])

In [85]:
weights.shape

torch.Size([3, 4, 6])

In [86]:
weights[0].size()

torch.Size([4, 6])

In [87]:
weights

tensor([[[0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667]],

        [[0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667]],

        [[0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667]]],
       grad_fn=<TransposeBackward0>)